api-version: '1.15'

name: PalaceHomes

main: br.com.gamespalace.PalaceHomes

version: 1.0

author: enzozbestetti

commands:
  sethome:
    description: Adiciona uma nova casa à lista do jogador
  home:
    description: Teleporta o jogar para a casa selecionada / Abre a GUI de casas
  delhome:
    description: Remove uma casa da lista do jogador


